

spring:
  datasource:
    #url: jdbc:postgresql://localhost:5432/kunde
    #username: postgres
    #password: 321
    url: jdbc:postgresql://monorail.proxy.rlwy.net:50679/railway
    username: postgres
    password: GGFf125B2FdEFC6DFfBC6ecEFc6AaBgb

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non_contextual_creation: true

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: root
      password: root

  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 150MB

server:
  error:
    include-message: always
port: 8080
